### ISSUE TITLE
Doesn't encode or decode correctly

### ISSUE THREAD

**Issue by lenazh** [olagrottvik/encdec8b10b#7]
The sequences encoded by this python 8b10b encoder are not recognized by the firmware - 8b10b decoder won't align. Known valid sequences that are generated by the hardware (and are decoded in firmware correctly) are not recognized by this python module.

**Comment by lenazh** [comment]
For example, it encodes K.28.1 as either 0x27c or 0x183. The correct 10b codes for K.28.1 are 0x0f9 or 0x306.
```
running_disp, encoded = EncDec8B10B.enc_8b10b(0x3c, 0, 1)
print(f'disp={running_disp}, 10b={encoded:x}')
disp=1, 10b=27c

running_disp, encoded = EncDec8B10B.enc_8b10b(0x3c, 1, 1)
>>> print(f'disp={running_disp}, 10b={encoded:x}')
disp=0, 10b=183
```

**Comment by olagrottvik** [comment]
You will notice that your example codes are simply bit-reversed from what is produced by this module. This is how Chuck Benz's decoder/encoder does it. Whether your firmware transmitter/receiver is constructing it as the less or the most significant bit first will give you the difference.

0xF9 = 00111111001 (bit-reverse) 1001111100 = 0x27C

**Comment by olagrottvik** [comment]
![image](https://user-images.githubusercontent.com/6538308/159715544-3af2de3d-bcc9-471c-9172-e8a909bc803e.png)

![image](https://user-images.githubusercontent.com/6538308/159715613-f87ed53b-0e35-46a0-a022-804430d3c2e3.png)

**Comment by argargreg** [comment]
Sorry but this doesn't seem to work. The running disparity is never updated:

```
from encdec8b10b import EncDec8B10B

running_disp = 1
bytes_to_enc = [1]*10;
for byte_to_enc in bytes_to_enc:
    running_disp, encoded = EncDec8B10B.enc_8b10b(byte_to_enc, running_disp, verbose=True)
    print('{:010b} RD={}'.format(encoded, running_disp))
```
